### ISSUE TITLE
Update all box shadows

### ISSUE THREAD

**Issue by aayushdutt** [Cyber-Labs/cdc-website#21]
Change all box shadows to: 
`box-shadow: -2px 8px 22px 0 rgba(0,0,0,.15);` 
This one looks more natural (used in `Home` page)

✅
![image](https://user-images.githubusercontent.com/25280541/58220061-27846b00-7cc2-11e9-8a2c-ed82490b04d9.png) 

❌
![image](https://user-images.githubusercontent.com/25280541/58220064-2fdca600-7cc2-11e9-8fd1-92560676f780.png)

**Comment by salonimohta** [comment]
Is there still a problem in box shadows after the latest commit?

**Comment by aayushdutt** [comment]
Nope, it's working great.
