### ISSUE TITLE
All the links in the footer, on clicking should take the user to the top of that page. 

### ISSUE THREAD

**Issue by AarushJ** [Cyber-Labs/cdc-website#25]
**Current behavior:** All links in the first column of links in the footer(Home, For Companies, For Students, For Alumni, Policies, Placement Stats, Contact Us) open the corresponding page, scrolled down to the bottom. 

**Required behaviour:** All links in the first column of links in the footer(Home, For Companies, For Students, For Alumni, Policies, Placement Stats, Contact Us) should open the top of the corresponding page.

**Comment by AarushJ** [comment]
@shivamsaraf look into this issue

**Comment by salonimohta** [comment]
This has been resolved
