### ISSUE TITLE
Placement policies page's headings and text both hanging anywhere(probably due to lack of responsiveness)

### ISSUE THREAD

**Issue by AarushJ** [Cyber-Labs/cdc-website#26]
Screenshot 1
![Screenshot from 2019-05-26 21-03-16](https://user-images.githubusercontent.com/17967678/58385196-465c6780-800a-11e9-8537-f4b81f9565c9.png)

Screenshot 2
![Screenshot from 2019-05-26 23-06-22](https://user-images.githubusercontent.com/17967678/58385256-0f3a8600-800b-11e9-8711-71df0533fabd.png)

Screenshot 3
![Screenshot from 2019-05-26 23-06-29](https://user-images.githubusercontent.com/17967678/58385258-0fd31c80-800b-11e9-887e-62fcd4ab72e2.png)

Screenshot 4
![Screenshot from 2019-05-26 23-06-36](https://user-images.githubusercontent.com/17967678/58385259-0fd31c80-800b-11e9-8c32-bfd6b7e53be0.png)

**Comment by salonimohta** [comment]
The page is very well responsive. This maybe because of adding lists. @shivamsaraf please look into this.

**Comment by salonimohta** [comment]
The headings are in place now.

@shivamsaraf There are no bullets in post-placement part of the webpage though. Please make it visible and modify that part

 
![image](https://user-images.githubusercontent.com/35621126/58415531-62104e00-809c-11e9-9a22-ebe5988dfcce.png)

**Comment by shivamsaraf** [comment]
Will see it once yr PR will be closed
